---
dist: xenial
language: python
python: 3.7
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libxml2-utils
install:
    - yarn install
    - pip install -r requirements.txt
cache:
  pip: true
  yarn: true
script:
   - yarn run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token:
   - secure: "pZio1bKt8WMYpGL6eQ661X+xz7un/3DjJfQvun/IHmbBgiDKZ6uDzYql01dvDMSDXHG69Fgou7waUPnlwSkrh/jXEdcJ35CJHMwpq8i5oKMZSY0jUEW+j3t8PU6XT32DObYbR2xD0yPMeRnMtZTu0ODGODBKZpULdT6HdQdvpzJ0SjXDdAewEkzwxchwFe3b0dkCKHRTQZARmoNq+6xR1K8lV7yZyhJKWEIDulklYB2Bh75Kre/z4lo3YWMzdOFzK7gvcJSdkhZTsFtqxIUgV+PAaRUggC1MO2LRCM10RSKyFGnfmCo3FXxaye7AGg+K1I39hdc6I8VrMXOI9U3/qHOrjlhRODCx5sAKdpNjlqpoB4OH8Xx9zRm2u+76RTJsXOudMThJLH0PJj7UePhhzfN7S9+NPFBRUZbDGsueFgMKBWbXkzdsZTkoiXcu8tU7OT4WPGi7gbaIhHMq9fdGx56N0jClOY/EF65bqfAKYiLsNYZSwB9uGIQ7gFFRcoxuBmauqvi6WbhAQE1ql+zr4R6TEvJgIZrVkgTWnjp+2cK0jnzlC1vP4XpAyxjyKzPcimKXgArYkNBZy38zWBpCcfXBsN7HKmu1ztsQnfr0p+jxZOJyQssmGnS0c5O9tfdGAueYH1/cAh9dzPQkaIYtg5V2tWHSANdzi1OntOPgruc="
  keep_history: true
  local_dir: docs/.vuepress/dist
  target_branch: gh-pages
  on:
    branch: testing
