dist: xenial
cache:
  yarn: true
  directories:
    - node_modules
script:
    - yarn run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token:
    secure: "jJIe+bE/a97rzuTgAXBtIzHpU1O7+UJtsz8FeMDrifcyLpiRFa+W+ykD+6fiYPdVvkpwxjYbKypC/9dxu9DVcId7nsZ3f1nNU0NJIrn5Nox4FwdQnCTN0+KU2fphH4ytXvmeswFbiH8PTS+FMLRsZKt4xdH6oq8rQyItq7k8lTscJ3u1L8AuCwsrZSJp+fVI9S7/9CyYdKCdxUhuIUzkPQEGCjV62TEYEnpUGTcC047P+mF5iwi6/+076T+lStwhkcAZXdkxsp9eSOL26u4yOccwNnEJjB7C1zjvcZ3lZeKOxOdj96Z3iH0k38IIdEa/Lo551yl8u4CKovkRoEtjuqdXodKqu8cnAygO7Nfn8Lc79ajZfhGC8evOkF5ErqFfYT54ZSfgN4daEmxqIrGdoe8MMZbBy8sXM/6B9CNyLXJvSRqtD0esRZzYQeHfFtZGi5S4JDoMmxcWZvdX0noSvPHsiwu4A3QVaYoLzEa1ykwZFCPpXJwrYVdPakHsRQY5Xs1SFCR956k3WxCN/0DaUsK3TkKs7t5FIKzh70/X84QNeW1FBxRm9+8jk5EEWLcd9N9vaK+eZAIzi1X1YgD73LfKxXugMu0lrbdT6pIXHn8ibN8EYItTe8E74mQsE2jaW4MJf6vanzsuXnQk0uzpSKAcJjIAtM3ioj5P6vXDjxg="
  keep_history: true
  local_dir: docs/.vuepress/dist
  target_branch: gh-pages
